from __future__ import annotations

from dataclasses import dataclass
import json

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_groq import ChatGroq

from app.core.config import settings
from app.core.json_utils import parse_json_object
from app.core.prompts import load_prompt
from app.graph.state import AgentState


def _bundle_from_files(files: dict[str, str]) -> str:
    sections: list[str] = []
    for relative_path, content in files.items():
        sections.append(f"## {relative_path}\n\n```text\n{content}\n```")
    return "\n\n".join(sections)


def _initial_files(project_name: str) -> dict[str, str]:
    return {
        "README.md": f"# {project_name}\n\nGenerated by DevCrew AI.",
        "requirements.txt": "fastapi\nuvicorn[standard]\npython-jose[cryptography]\npasslib[bcrypt]\npydantic\n",
        "app/__init__.py": "",
        "app/main.py": (
            "from fastapi import FastAPI\n"
            "from app.routes.auth import router as auth_router\n"
            "from app.routes.todos import router as todos_router\n\n"
            f"app = FastAPI(title=\"{project_name}\")\n\n"
            "app.include_router(auth_router, prefix=\"/auth\", tags=[\"auth\"])\n"
            "app.include_router(todos_router, prefix=\"/todos\", tags=[\"todos\"])\n\n"
            "@app.get(\"/health\")\n"
            "def health():\n"
            "    return {\"status\": \"ok\"}\n"
        ),
        "app/core/__init__.py": "",
        "app/core/security.py": (
            "from datetime import datetime, timedelta, timezone\n"
            "from jose import jwt\n"
            "from passlib.context import CryptContext\n\n"
            "SECRET_KEY = \"dev-secret\"\n"
            "ALGORITHM = \"HS256\"\n"
            "ACCESS_TOKEN_EXPIRE_MINUTES = 15\n"
            "pwd_context = CryptContext(schemes=[\"bcrypt\"], deprecated=\"auto\")\n\n"
            "def hash_password(password: str) -> str:\n"
            "    return pwd_context.hash(password)\n\n"
            "def verify_password(plain_password: str, hashed_password: str) -> bool:\n"
            "    return pwd_context.verify(plain_password, hashed_password)\n\n"
            "def create_access_token(subject: str) -> str:\n"
            "    expires_at = datetime.now(timezone.utc) + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)\n"
            "    payload = {\"sub\": subject, \"exp\": expires_at}\n"
            "    return jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)\n"
        ),
        "app/models.py": (
            "from pydantic import BaseModel\n\n"
            "class Token(BaseModel):\n"
            "    access_token: str\n"
            "    token_type: str = \"bearer\"\n\n"
            "class TodoCreate(BaseModel):\n"
            "    title: str\n"
            "    done: bool = False\n\n"
            "class TodoRead(TodoCreate):\n"
            "    id: int\n"
        ),
        "app/routes/__init__.py": "",
        "app/routes/auth.py": (
            "from fastapi import APIRouter, HTTPException\n"
            "from pydantic import BaseModel\n"
            "from app.core.security import create_access_token, hash_password, verify_password\n\n"
            "router = APIRouter()\n"
            "USERS = {\"admin\": hash_password(\"admin123\")}\n\n"
            "class LoginRequest(BaseModel):\n"
            "    username: str\n"
            "    password: str\n\n"
            "@router.post(\"/login\")\n"
            "def login(payload: LoginRequest):\n"
            "    stored_password = USERS.get(payload.username)\n"
            "    if not stored_password or not verify_password(payload.password, stored_password):\n"
            "        raise HTTPException(status_code=401, detail=\"Invalid credentials\")\n"
            "    return {\"access_token\": create_access_token(payload.username), \"token_type\": \"bearer\"}\n"
        ),
        "app/routes/todos.py": (
            "from fastapi import APIRouter, Depends, HTTPException\n"
            "from app.models import TodoCreate, TodoRead\n\n"
            "router = APIRouter()\n"
            "TODOS: list[TodoRead] = []\n"
            "NEXT_ID = 1\n\n"
            "def require_user() -> str:\n"
            "    return \"admin\"\n\n"
            "@router.get(\"/\", response_model=list[TodoRead])\n"
            "def list_todos(user: str = Depends(require_user)):\n"
            "    return TODOS\n\n"
            "@router.post(\"/\", response_model=TodoRead)\n"
            "def create_todo(todo: TodoCreate, user: str = Depends(require_user)):\n"
            "    global NEXT_ID\n"
            "    item = TodoRead(id=NEXT_ID, title=todo.title, done=todo.done)\n"
            "    TODOS.append(item)\n"
            "    NEXT_ID += 1\n"
            "    return item\n"
        ),
        "tests/test_health.py": (
            "from fastapi.testclient import TestClient\n"
            "from app.main import app\n\n"
            "client = TestClient(app)\n\n"
            "def test_health():\n"
            "    response = client.get(\"/health\")\n"
            "    assert response.status_code == 200\n"
            "    assert response.json() == {\"status\": \"ok\"}\n"
        ),
    }


def _revised_files(project_name: str) -> dict[str, str]:
    files = _initial_files(project_name)
    files["app/core/security.py"] = (
        "from datetime import datetime, timedelta, timezone\n"
        "import os\n"
        "from jose import jwt\n"
        "from passlib.context import CryptContext\n\n"
        "SECRET_KEY = os.getenv(\"JWT_SECRET\")\n"
        "if not SECRET_KEY:\n"
        "    raise RuntimeError(\"JWT_SECRET must be set\")\n"
        "ALGORITHM = \"HS256\"\n"
        "ACCESS_TOKEN_EXPIRE_MINUTES = 15\n"
        "pwd_context = CryptContext(schemes=[\"bcrypt\"], deprecated=\"auto\")\n\n"
        "def hash_password(password: str) -> str:\n"
        "    return pwd_context.hash(password)\n\n"
        "def verify_password(plain_password: str, hashed_password: str) -> bool:\n"
        "    return pwd_context.verify(plain_password, hashed_password)\n\n"
        "def create_access_token(subject: str) -> str:\n"
        "    expires_at = datetime.now(timezone.utc) + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)\n"
        "    payload = {\"sub\": subject, \"exp\": expires_at}\n"
        "    return jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)\n"
    )
    files["README.md"] = (
        f"# {project_name}\n\n"
        "Generated by DevCrew AI. Set JWT_SECRET before running the application."
    )
    return files


@dataclass
class CoderAgent:
    def _client(self) -> ChatGroq:
        return ChatGroq(model=settings.groq_model, groq_api_key=settings.groq_api_key, temperature=0)

    def _fallback(self, state: AgentState) -> dict[str, object]:
        project_name = state.get("project_name", "FastAPI Project")
        revision_count = int(state.get("revision_count", 0))

        files = _revised_files(project_name) if revision_count > 0 else _initial_files(project_name)
        bundle_markdown = _bundle_from_files(files)
        return {
            "project_files": files,
            "bundle_markdown": bundle_markdown,
            "final_summary": (
                f"Generated {len(files)} files for {project_name}. Revision count: {revision_count}."
            ),
        }

    def run(self, state: AgentState) -> dict[str, object]:
        if settings.groq_api_key:
            prompt = load_prompt("coder")
            payload_text = json.dumps(
                {
                    "project_name": state.get("project_name"),
                    "user_request": state.get("user_request"),
                    "tasks": state.get("tasks", []),
                    "review": state.get("review", {}),
                    "revision_count": state.get("revision_count", 0),
                },
                indent=2,
            )
            response = self._client().invoke(
                [
                    SystemMessage(content=prompt),
                    HumanMessage(content=payload_text),
                ]
            )
            payload = parse_json_object(str(response.content))
        else:
            payload = self._fallback(state)

        files = {str(key): str(value) for key, value in dict(payload.get("project_files", {})).items()}
        return {
            "project_files": files,
            "bundle_markdown": str(payload.get("bundle_markdown", _bundle_from_files(files))),
            "final_summary": str(payload.get("final_summary", "")),
        }
