from __future__ import annotations

from dataclasses import dataclass

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_groq import ChatGroq

from backend.app.core.config import settings
from backend.app.core.json_utils import parse_json_object
from backend.app.core.prompts import load_prompt
from backend.app.graph.state import AgentState


def _fallback_documentation(state: AgentState) -> dict[str, object]:
    architecture = dict(state.get("architecture", {}))
    project_name = str(state.get("project_name", "DevCrew AI Project"))
    docs = f"""# {project_name}

## Overview

This project was generated by DevCrew AI Stage 2.

## Architecture

- Backend: {architecture.get('backend', 'FastAPI')}
- Database: {architecture.get('database', 'SQLite')}
- Authentication: {architecture.get('authentication', 'JWT')}

## Installation

1. Create a virtual environment.
2. Install dependencies from `requirements.txt`.
3. Set `JWT_SECRET` in your environment.
4. Run the app with `uvicorn app.main:app --reload`.

## API Overview

- `GET /health`
- `POST /auth/login`
- `GET /todos`
- `POST /todos`

## Future Improvements

- Add database migrations.
- Add refresh tokens.
- Add pagination and filtering.
"""
    docs_files = {
        "README.md": docs,
        "docs/architecture.md": "\n".join(str(note) for note in state.get("research_notes", [])),
    }
    return {"documentation": docs, "docs_files": docs_files, "final_summary": "Generated project documentation."}


@dataclass
class DocumentationAgent:
    def _client(self) -> ChatGroq:
        return ChatGroq(model=settings.groq_model, groq_api_key=settings.groq_api_key, temperature=0)

    def run(self, state: AgentState) -> dict[str, object]:
        if settings.groq_api_key:
            prompt = load_prompt("documentation")
            payload_text = {
                "project_name": state.get("project_name"),
                "architecture": state.get("architecture", {}),
                "research_notes": state.get("research_notes", []),
                "project_files": state.get("project_files", {}),
            }
            response = self._client().invoke([SystemMessage(content=prompt), HumanMessage(content=str(payload_text))])
            payload = parse_json_object(str(response.content))
        else:
            payload = _fallback_documentation(state)

        docs_files = dict(payload.get("docs_files", {}))
        project_files = dict(state.get("project_files", {}))
        project_files.update(docs_files)

        return {
            "documentation": str(payload.get("documentation", "")),
            "project_files": project_files,
            "documentation_summary": str(payload.get("final_summary", "Generated project documentation.")),
            "final_summary": str(payload.get("final_summary", "Generated project documentation.")),
        }